In [1]:
!pip3 install numpy

In [2]:
import numpy as np
import multiprocessing

def multiply_matrices(start_row, end_row, matrix_a, matrix_b):
  """
  Args:
    start_row: The start row index of the block to multiply.
    end_row: The end row index of the block to multiply.
    matrix_a: The first matrix.
    matrix_b: The second matrix.

  Returns:
    The product of the block and the second matrix.
  """

  C = np.zeros_like(matrix_b)
  for i in range(start_row, end_row):
    for j in range(matrix_b.shape[0]):
      C[i, j] = np.sum(matrix_a[i, :] * matrix_b[:,j].T)

  return C

def main():
  matrix_size=1000
  num_threads = multiprocessing.cpu_count()
  print(num_threads)
  # Create two random matrices.
  matrix_a = np.random.randint(4, size=(matrix_size,matrix_size))
  matrix_b = np.random.randint(4, size=(matrix_size,matrix_size))
  print(matrix_a, "\n", matrix_b)
  # Create a pool of worker processes.
  workers = matrix_size//num_threads if matrix_size//num_threads>1 else 2
  print(workers)
  pool = multiprocessing.Pool(workers)

  # Divide the workload into smaller tasks.
  tasks = []
  for i in range(0, matrix_a.shape[0], workers):
    start_row = i
    end_row = min(i + (workers), matrix_a.shape[0])
    task = (start_row, end_row, matrix_a, matrix_b)
    tasks.append(task)

  # Start the worker processes and get the results asynchronously.
  results = [pool.apply_async(multiply_matrices, args=task) for task in tasks]

  # Combine the results from the worker processes.
  C = np.zeros_like(matrix_a)
  for result in results:
    print("\n result.get()",result.get())
    C += result.get()
  print(C)
  np.savetxt(X=C, fname="resultant.txt")

if __name__ == "__main__":
  main()

2
[[3 1 3 ... 0 2 0]
 [1 0 0 ... 0 2 0]
 [2 3 3 ... 0 2 3]
 ...
 [1 0 3 ... 1 2 0]
 [1 1 3 ... 1 1 0]
 [3 3 0 ... 1 2 3]] 
 [[3 0 3 ... 2 1 3]
 [2 3 0 ... 2 1 0]
 [3 1 0 ... 2 3 0]
 ...
 [0 0 0 ... 0 1 2]
 [1 2 1 ... 1 2 2]
 [3 1 3 ... 3 2 3]]
500

 result.get() [[2287 2215 2357 ... 2276 2322 2271]
 [2233 1977 2260 ... 2158 2148 2201]
 [2210 2173 2181 ... 2290 2215 2282]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]

 result.get() [[   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [2290 2155 2265 ... 2233 2262 2346]
 [2236 2179 2249 ... 2208 2185 2149]
 [2278 2105 2309 ... 2313 2291 2295]]
[[2287 2215 2357 ... 2276 2322 2271]
 [2233 1977 2260 ... 2158 2148 2201]
 [2210 2173 2181 ... 2290 2215 2282]
 ...
 [2290 2155 2265 ... 2233 2262 2346]
 [2236 2179 2249 ... 2208 2185 2149]
 [2278 2105 2309 ... 2313 2291 2295]]
